### PR TITLE
Function tests

### PR DESCRIPTION
**Pull request by Yuri211200**
All porosity tests are running correctly and are almost concluded, only need to improve them with object oriented programming in the future. Besides, just update the first function test in water saturation section and they work perfectly. Maybe it has enough tests to merge.

### CODE REVIEW

**Comment by mmramos** [comment]
Ok Yuri, It`s clear that

**Comment by mmramos** [comment]
Cool Yuri, so, making it clear that future modifications will be made to make the code cleaner in terms of variables, I believe that the main point to be modified would be about `np.random.uniform(low=1.0, high=3.0, size=None)`,  which can be replaced by `np.random.uniform(low=1.0, high=3.0, size=15)`. Below is an image of the process.

similar to current one
image

suggestion
image

**Comment by mmramos** [comment]
About the warnings/errors, I really don't know if the `try:` and `except:` syntax is the best, (or the only one),
neither if the text is the correct one,
but for me it's ok. Thank you for your suggestions in this topic!

**Review by mmramos — APPROVED** [review]
For me it's ok to go!

**Comment by Yuri211200** [comment]
Thanks, Mario!

**Pull request merged**
